name: Build with NPM

on:
  # Push into branches 'main' and 'dev'
  push:
    branches: [ main, dev ]
    paths-ignore:
    - '**.md'
    - '**.*ignore'
  # PR into branch 'main'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**.*ignore'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Enable futher node.js versions
        # - as long as no release is published, only the most current is used
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
